[package]
name = "image-effects"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.93"
base64 = "0.22.1"
image = "0.25.2"

[dependencies.web-sys]
version = "0.3.4"
features = ["console"]